[project]
name = "octodns-mikrotik"
revision = "1.0"

[profiles.default]
MIKROTIK_HOST = { description = "MikroTik host", required = false }
MIKROTIK_USER = { description = "MikroTik user", required = true }
MIKROTIK_PASSWORD = { description = "MikroTik password", required = true }
